overwrite: true
schema: 'https://shopify.dev/admin-graphql-direct-proxy/2025-07'
documents: './src/**/*.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-graphql-request'
    config:
      scalars:
        DateTime: string
        HTML: string
        URL: string
        Decimal: number
